# Function to translate COW country codes to PITF country codes
# Based on f.cowtopitfit.R written by Jay Ulfelder 2014-09-02 (Jay Ulfelder)
# This version works a bit differently
# Chad Hazlett 28 Oct 2017
# MOdified 2018 to add South Sudan (626)
cowtopitfit <- function(cowcodedata, yeardata) {
  sftgcode=numeric(length(cowcodedata))
  "AFG" -> sftgcode[cowcodedata==700]
  "ALB" -> sftgcode[cowcodedata==339]
  "ALG" -> sftgcode[cowcodedata==615]
  "ANG" -> sftgcode[cowcodedata==540]
  "ARG" -> sftgcode[cowcodedata==160]
  "ARM" -> sftgcode[cowcodedata==371]
  "AUL" -> sftgcode[cowcodedata==900]
  "AUS" -> sftgcode[cowcodedata==305]
  "AZE" -> sftgcode[cowcodedata==373]
  "BAH" -> sftgcode[cowcodedata==692]
  "BAR" -> sftgcode[cowcodedata==53]
  "BEL" -> sftgcode[cowcodedata==211]
  "BEN" -> sftgcode[cowcodedata==434]
  "BFO" -> sftgcode[cowcodedata==439]
  "BHM" -> sftgcode[cowcodedata==31]
  "BHU" -> sftgcode[cowcodedata==760]
  "BLR" -> sftgcode[cowcodedata==370]
  "BLZ" -> sftgcode[cowcodedata==80]
  "BNG" -> sftgcode[cowcodedata==771]
  "BOL" -> sftgcode[cowcodedata==145]
  "BOS" -> sftgcode[cowcodedata==346]
  "BOT" -> sftgcode[cowcodedata==571]
  "BRA" -> sftgcode[cowcodedata==140]
  "BUI" -> sftgcode[cowcodedata==516]
  "BUL" -> sftgcode[cowcodedata==355]
  "CAM" -> sftgcode[cowcodedata==811]
  "CAN" -> sftgcode[cowcodedata==20]
  "CAO" -> sftgcode[cowcodedata==471]
  "CEN" -> sftgcode[cowcodedata==482]
  "CHA" -> sftgcode[cowcodedata==483]
  "CHL" -> sftgcode[cowcodedata==155]
  "CHN" -> sftgcode[cowcodedata==710]
  "COL" -> sftgcode[cowcodedata==100]
  "COM" -> sftgcode[cowcodedata==581]
  "CON" -> sftgcode[cowcodedata==484]
  "COS" -> sftgcode[cowcodedata==94]
  "CRO" -> sftgcode[cowcodedata==344]
  "CUB" -> sftgcode[cowcodedata==40]
  "CYP" -> sftgcode[cowcodedata==352]
  "CZE" -> sftgcode[cowcodedata==315]
  "CZR" -> sftgcode[cowcodedata==316]
  "DEN" -> sftgcode[cowcodedata==390]
  "DJI" -> sftgcode[cowcodedata==522]
  "DOM" -> sftgcode[cowcodedata==42]
  "ZAI" -> sftgcode[cowcodedata==490]
  "DRV" -> sftgcode[cowcodedata==816 & yeardata <= 1975]
  "VIE" -> sftgcode[cowcodedata==816 & yeardata >= 1976]
  "VIE" -> sftgcode[cowcodedata==818]
  "ECU" -> sftgcode[cowcodedata==130]
  "EGY" -> sftgcode[cowcodedata==651]
  "EQG" -> sftgcode[cowcodedata==411]
  "ERI" -> sftgcode[cowcodedata==531]
  "EST" -> sftgcode[cowcodedata==366]
  "ETH" -> sftgcode[cowcodedata==530 & yeardata <= 1992]
  "ETI" -> sftgcode[cowcodedata==530 & yeardata >= 1993]
  "ETH" -> sftgcode[cowcodedata==529]
  "ETM" -> sftgcode[cowcodedata==860]
  "FIN" -> sftgcode[cowcodedata==375]
  "FJI" -> sftgcode[cowcodedata==950]
  "FRN" -> sftgcode[cowcodedata==220]
  "GAB" -> sftgcode[cowcodedata==481]
  "GAM" -> sftgcode[cowcodedata==420]
  "GDR" -> sftgcode[cowcodedata==265]
  "GFR" -> sftgcode[cowcodedata==260 & yeardata <= 1989]
  "GER" -> sftgcode[cowcodedata==260 & yeardata >= 1990]
  "GER" -> sftgcode[cowcodedata==255]
  "GHA" -> sftgcode[cowcodedata==452]
  "GNB" -> sftgcode[cowcodedata==404]
  "GRC" -> sftgcode[cowcodedata==350]
  "GUA" -> sftgcode[cowcodedata==90]
  "GUI" -> sftgcode[cowcodedata==438]
  "GUY" -> sftgcode[cowcodedata==110]
  "HAI" -> sftgcode[cowcodedata==41]
  "HON" -> sftgcode[cowcodedata==91]
  "HUN" -> sftgcode[cowcodedata==310]
  "ICE" -> sftgcode[cowcodedata==395]
  "IND" -> sftgcode[cowcodedata==750]
  "INS" -> sftgcode[cowcodedata==850]
  "IRE" -> sftgcode[cowcodedata==205]
  "IRN" -> sftgcode[cowcodedata==630]
  "IRQ" -> sftgcode[cowcodedata==645]
  "ISR" -> sftgcode[cowcodedata==666]
  "ITA" -> sftgcode[cowcodedata==325]
  "JAM" -> sftgcode[cowcodedata==51]
  "JOR" -> sftgcode[cowcodedata==663]
  "JPN" -> sftgcode[cowcodedata==740]
  "KEN" -> sftgcode[cowcodedata==501]
  "KUW" -> sftgcode[cowcodedata==690]
  "KYR" -> sftgcode[cowcodedata==703]
  "KZK" -> sftgcode[cowcodedata==705]
  "LAO" -> sftgcode[cowcodedata==812]
  "LAT" -> sftgcode[cowcodedata==367]
  "LBR" -> sftgcode[cowcodedata==450]
  "LEB" -> sftgcode[cowcodedata==660]
  "LES" -> sftgcode[cowcodedata==570]
  "LIB" -> sftgcode[cowcodedata==620]
  "LIT" -> sftgcode[cowcodedata==368]
  "MAA" -> sftgcode[cowcodedata==435]
  "MAC" -> sftgcode[cowcodedata==343]
  "MAG" -> sftgcode[cowcodedata==580]
  "MAL" -> sftgcode[cowcodedata==820]
  "MAS" -> sftgcode[cowcodedata==590]
  "MAW" -> sftgcode[cowcodedata==553]
  "MEX" -> sftgcode[cowcodedata==70]
  "MLD" -> sftgcode[cowcodedata==359]
  "MLI" -> sftgcode[cowcodedata==432]
  "MON" -> sftgcode[cowcodedata==712]
  "MOR" -> sftgcode[cowcodedata==600]
  "MYA" -> sftgcode[cowcodedata==775]
  "MZM" -> sftgcode[cowcodedata==541]
  "NAM" -> sftgcode[cowcodedata==565]
  "NEP" -> sftgcode[cowcodedata==790]
  "NEW" -> sftgcode[cowcodedata==920]
  "NIC" -> sftgcode[cowcodedata==93]
  "NIG" -> sftgcode[cowcodedata==475]
  "NIR" -> sftgcode[cowcodedata==436]
  "NOR" -> sftgcode[cowcodedata==385]
  "NTH" -> sftgcode[cowcodedata==210]
  "OMA" -> sftgcode[cowcodedata==698]
  "PKS" -> sftgcode[cowcodedata==769]
  "PKS" -> sftgcode[cowcodedata==770 & yeardata <= 1971]
  "PAK" -> sftgcode[cowcodedata==770 & yeardata >= 1972]
  "PAN" -> sftgcode[cowcodedata==95]
  "PAR" -> sftgcode[cowcodedata==150]
  "PER" -> sftgcode[cowcodedata==135]
  "PHI" -> sftgcode[cowcodedata==840]
  "PNG" -> sftgcode[cowcodedata==910]
  "POL" -> sftgcode[cowcodedata==290]
  "POR" -> sftgcode[cowcodedata==235]
  "QAT" -> sftgcode[cowcodedata==694]
  "ROK" -> sftgcode[cowcodedata==732]
  "KOR" -> sftgcode[cowcodedata==730]
  "RUM" -> sftgcode[cowcodedata==360]
  "USS" -> sftgcode[cowcodedata==364]
  "USS" -> sftgcode[cowcodedata==365 & yeardata <= 1991 & yeardata >= 1917]
  "RUS" -> sftgcode[cowcodedata==365 & (yeardata >= 1992 | yeardata <= 1916)]
  "RVN" -> sftgcode[cowcodedata==817]
  "RWA" -> sftgcode[cowcodedata==517]
  "SSD" -> sftgcode[cowcodedata==626]
  "SAF" -> sftgcode[cowcodedata==560]
  "SAL" -> sftgcode[cowcodedata==92]
  "SAU" -> sftgcode[cowcodedata==670]
  "SEN" -> sftgcode[cowcodedata==433]
  "SIE" -> sftgcode[cowcodedata==451]
  "SIN" -> sftgcode[cowcodedata==830]
  "SLO" -> sftgcode[cowcodedata==317]
  "SLV" -> sftgcode[cowcodedata==349]
  "SOL" -> sftgcode[cowcodedata==940]
  "SOM" -> sftgcode[cowcodedata==520]
  "SPN" -> sftgcode[cowcodedata==230]
  "SRI" -> sftgcode[cowcodedata==780]
  "SUD" -> sftgcode[cowcodedata==625]
  "SUR" -> sftgcode[cowcodedata==115]
  "SWA" -> sftgcode[cowcodedata==572]
  "SWD" -> sftgcode[cowcodedata==380]
  "SWZ" -> sftgcode[cowcodedata==225]
  "SYR" -> sftgcode[cowcodedata==652]
  "TAJ" -> sftgcode[cowcodedata==702]
  "TAW" -> sftgcode[cowcodedata==713]
  "TAZ" -> sftgcode[cowcodedata==510]
  "THI" -> sftgcode[cowcodedata==800]
  "TKM" -> sftgcode[cowcodedata==701]
  "TOG" -> sftgcode[cowcodedata==461]
  "TRI" -> sftgcode[cowcodedata==52]
  "TUN" -> sftgcode[cowcodedata==616]
  "TUR" -> sftgcode[cowcodedata==640]
  "UAE" -> sftgcode[cowcodedata==696]
  "UGA" -> sftgcode[cowcodedata==500]
  "USA" -> sftgcode[cowcodedata==2]
  "UKG" -> sftgcode[cowcodedata==200]
  "UKR" -> sftgcode[cowcodedata==369]
  "URU" -> sftgcode[cowcodedata==165]
  "UZB" -> sftgcode[cowcodedata==704]
  "VEN" -> sftgcode[cowcodedata==101]
  "YEM" -> sftgcode[cowcodedata==679]
  "YEM" -> sftgcode[cowcodedata==678 & yeardata >= 1990]
  "YAR" -> sftgcode[cowcodedata==678 & yeardata <= 1989]
  "YPR" -> sftgcode[cowcodedata==680]
  "YUG" -> sftgcode[cowcodedata==345 & yeardata <= 1991]
  "YGS" -> sftgcode[cowcodedata==345 & yeardata >= 1992 & yeardata <= 2005]
  "SRB" -> sftgcode[cowcodedata==345 & yeardata >= 2006]
  "SRB" -> sftgcode[cowcodedata==342]
  "MNE" -> sftgcode[cowcodedata==348]
  "ZAM" -> sftgcode[cowcodedata==551]
  "ZIM" -> sftgcode[cowcodedata==552]
  "MNE" -> sftgcode[cowcodedata==341]
  "KOS" -> sftgcode[cowcodedata==347]
  "IVO" -> sftgcode[cowcodedata==437]
  "PRK" -> sftgcode[cowcodedata==731]
  "GRG" -> sftgcode[cowcodedata==372]
  return(sftgcode)
}